; ==============================================================================
; PlatformIO Project Configuration File
; Project: 01_monster_truck_crash
; Target: Arduino Uno / Arduino Nano (ATmega328P)
; Description: Ultrasonic Monster Truck Crash Intensity Sensor with Buzzer & LEDs
; ==============================================================================

[platformio]
default_envs = uno
description = Monster Truck Crash Sensor: Buzzer and LEDs speed up as truck drives away toward the crash pile at 10cm!

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
monitor_filters = time, colorize

[env:nano]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
monitor_filters = time, colorize

[env:nano_old_bootloader]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
monitor_filters = time, colorize
